// Authenication
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_FAILED = "SIGNOUT_FAILED";

// About
export const FETCH_ABOUT = "FETCH_ABOUT";
export const UPDATE_ABOUT_SUCCESS = "UPDATE_ABOUT_SUCCESS"; 
export const UPDATE_ABOUT_FAILED = "UPDATE_ABOUT_FAILED"; 

// FaithLift
export const FETCH_FAITHLIFT = "FETCH_FAITHLIFT";
export const UPDATE_FAITHLIFT_SUCCESS = "UPDATE_FAITHLIFT_SUCCESS"; 
export const UPDATE_FAITHLIFT_FAILED = "UPDATE_FAITHLIFT_FAILED"; 

// Socials
export const FETCH_SOCIALS = "FETCH_SOCIALS";
export const UPDATE_SOCIALS_SUCCESS = "UPDATE_SOCIALS_SUCCESS"; 
export const UPDATE_SOCIALS_FAILED = "UPDATE_SOCIALS_FAILED"; 

// Slideshow
export const FETCH_SLIDESHOW = "FETCH_SLIDESHOW";
export const UPLOAD_SLIDESHOW = "UPLOAD_SLIDESHOW";
export const PROGRESS = "PROGRESS";
export const ADD_SLIDESHOW_SUCCESS = "ADD_SLIDESHOW_SUCCESS"; 
export const ADD_SLIDESHOW_FAILED = "ADD_SLIDESHOW_FAILED";
export const RESET= "RESET"; 